---
# TODO: ansible is a dependency for this whole process, just remove this
- name: ansible
  community.general.pacman:
    name: ansible-core ansible
    state: present

# TODO: This will probably have to be moved. An internet connection is a
# prerequisite for installing any packages at all
- name: networkmanager
  community.general.pacman:
    name: networkmanager
    state: present
# TODO: enable networkmanager - handler?
# connect to wifi network - probably never include this behavior

# TODO:MISC configurations - ansible.builtin.lineinfile?
# edit /etc/default/grub to make grub text readable on high dpi screen
# GRUB_GFXMODE=1024x768
# afterwards run grub-mkconfig -o /boot/grub/grub.cfg
# handler?
#
# add delay after failed login - ansible.builtin.lineinfile?
# edit /etc/pam.d/system-login
# auth optional pam_faildelay.so delay=2000000

- name: vim
  community.general.pacman:
    name: vim
    state: present

- name: sudo
  community.general.pacman:
    name: sudo
    state: present
# TODO: set default editor in visudo - ansible.builtin.lineinfile?
# Defaults  editor=/usr/bin/vim, !env_editor
# TODO: add user to sudoers. is there a visudo module?

- name: man
  community.general.pacman:
    name: man
    state: present

- name: microcode updates
  community.general.pacman:
    name: intel-ucode
    state: present
# TODO: run
# $ grub-mkconfig -o /boot/grub/grub.cfg
# afterwards to remake grub config - handler?

- name: openssh
  community.general.pacman:
    name: openssh
    state: present
# TODO: edit /etc/ssh/sshd_config to disable root login
# PermitRootLogin no
# If this is done via dotfiles ensure no secrets are exposed - ansible.builtin.lineinfile?

- name: wayland
  community.general.pacman:
    name: wayland
    state: present

- name: wl-clipboard
  community.general.pacman:
    name: wl-clipboard
    state: present
# TODO: configure vim to use wayland clipboard

- name: sway
  community.general.pacman:
    name: sway
    state: present

- name: waybar
  community.general.pacman:
    name: waybar
    state: present

- name: bemenu
  community.general.pacman:
    name: bemenu
    state: present

- name: kitty
  community.general.pacman:
    name: kitty
    state: present

- name: fish
  community.general.pacman:
    name: fish
    state: present

- name: light
  community.general.pacman:
    name: light
    state: present

- name: firefox
  community.general.pacman:
    name: firefox
    state: present
# TODO: install extensions. Can this be captured by dotfiles?

- name: git
  community.general.pacman:
    name: git
    state: present

- name: fonts
  community.general.pacman:
    name: noto-fonts-emoji ttf-font-awesome
    state: present

- name: vscode
  community.general.pacman:
    name: code
    state: present

- name: rustup
  community.general.pacman:
    name: rustup
    state: present
# TODO: install rust via rustup
# rustup default stable

- name: zig
  community.general.pacman:
    name: zig
    state: present

- name: unzip
  community.general.pacman:
    name: unzip
    state: present

- name: LaTeX
  community.general.pacman:
    name: texlive-most
    state: present

- name: neovim
  community.general.pacman:
    name: neovim
    state: present

- name: mupdf
  community.general.pacman:
    name: mupdf
    state: present

- name: libreoffice
  community.general.pacman:
    name: libreoffice
    state: present

# for AUR
# Note - needs option --needed
- name: base-devel
  community.general.pacman:
    name: base-devel
    state: present

### AUR ###
# TODO: aur helper or aur module
- name: rcm
  aur-helper:
    name: rcm
    state: present

- name: vim-plug
  aur-helper:
    name: vim-plug
    state: present
